server:
  port: 8888
spring:
  application:
    name: uaa
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
